### ISSUE TITLE
K8SSAND-1348 ⁃ Cluster can get into a deadlocked state, unable to recover without manual intervention

### ISSUE THREAD

**Issue by jakerobb** [k8ssandra/cass-operator#303] opened 2022-03-23 02:20 UTC
**What happened?**
Please see #302 for the full story. This is the "other issue I'll report separately" from step 4. We’re using cass-operator 1.5.1; I do not yet know if this is still a problem with the latest version. 

**Did you expect to see something different?**
I expected cass-operator to figure things out and bring our cluster up.

**How to reproduce it (as minimally and precisely as possible)**:
This one is tricky. First you need to get a cluster with a Cassandra pod in a bad state. Not allocating enough memory should do the trick. The bad node needs to be stuck in `Starting`.

Now, try to move one of the other pods to another node. It will get stuck in `Ready to Start`, unable to proceed because cass-operator is waiting on the other node.

I think, if there are other pods not in `Started`, cass-operator should probably give up on the "Starting" pod after some period of time and see if it can start one of the other ones first. Maybe there's a more sophisticated option here; I don't know what it would be.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1348) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1348
┆priority: Medium

**Comment by jsanda** [comment] 2022-03-23 02:24
@jakerobb can you please provide the version of cass-operator?

**Comment by burmanm** [comment] 2022-03-25 11:48
The problem is that we don't know for sure that "Starting" has failed and as such shouldn't start another node. Giving up "Starting" means we should kill the pod after some time and that time should be something what's maximum for a pod to start correctly. In some instances this could take a while and if we keep killing it the cluster would never start its nodes. 

So unless we can reliably say that the pod can't be started (or failed to start) in its current configuration we might not want to do anything. Otherwise we risk the state that the cluster will never boot up without a chance to even a manual recovery. The ticket in #302 mentions the part 4 as "Ready-to-Start" and this one talks about "Starting", but I'm assuming this one is the correct state. 

The #302 story is a bit odd since it involved manually messing up with resources (overriding cass-operator behavior) and there are probably lots of such scenarios where we can't automatically recover from, since we don't have information what happened.

**Comment by burmanm** [comment] 2022-03-25 13:53
We could in theory follow the logs, do you happen to have them that show easily what happened? Of course it would be even better if management-api would know that things have gone wrong, but logs / evidence / information helps to make at least some advancements.

**Comment by burmanm** [comment] 2022-09-20 06:43
Closing due to lack of information.

**Closed as completed by burmanm** 2022-09-20 06:43 UTC
Labels: bug
